import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  emojiMarker: {
    justifyContent: "center",
    alignItems: "center",
    fontSize: 32,
  },
  emojiText: {
    fontSize: 32,
    textAlign: "center",
  },
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  map: {
    flex: 1,
  },
  safeArea: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "transparent",
    pointerEvents: "box-none",
  },
  largePinContainer: {
    justifyContent: "center",
    alignItems: "center",
    fontSize: 32,
    backgroundColor: "transparent",
  },
  searchBar: {
    backgroundColor: "white",
    borderRadius: 10,
    zIndex: 2,
  },
  suggestionsList: {
    position: "absolute",
    top: 60,
    left: 10,
    right: 10,
    backgroundColor: "white",
    zIndex: 2,
  },
  suggestionItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  defaultPin: {
    justifyContent: "center",
    alignItems: "center",
    fontSize: 24,
  },
  pinText: {
    fontSize: 24,
    textAlign: "center",
  },
  actionButton: {
    backgroundColor: "#1E90FF",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    margin: 5,
    position: "relative",
    zIndex: 1,
  },
  actionButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
  },
  evMarker: {
    backgroundColor: "green",
    padding: 15,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    width: 60,
    height: 60,
  },
  evMarkerText: {
    fontSize: 24,
    color: "white",
    fontWeight: "bold",
  },
  chargerList: {
    position: "absolute",
    bottom: 100,
    left: 10,
    right: 10,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 10,
    maxHeight: 200,
    elevation: 5,
    zIndex: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  chargerItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
    alignItems: "center",
  },
  chargerText: {
    fontSize: 16,
    fontWeight: "bold",
  },
  popupContainer: {
    position: "absolute",
    bottom: 50,
    left: 10,
    right: 10,
    backgroundColor: "transparent",
    padding: 0,
    alignItems: "center",
  },
  infoBox: {
    padding: 15,
    borderRadius: 15,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    width: "100%",
    elevation: 5,
  },
  placeName: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#333",
  },
  distance: {
    fontSize: 15,
    color: "#666",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 8,
    color: "#444",
  },
  amenitiesScroll: {
    marginTop: 8,
    flexDirection: "row",
    marginBottom: 15,
  },
  amenityBox: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: "#4CAF50",
    borderRadius: 20,
    marginRight: 8,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 100,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  highlightedAmenityBox: {
    backgroundColor: "#1976D2",
    borderWidth: 2,
    borderColor: "#FFF",
  },
  amenityText: {
    fontSize: 14,
    color: "#fff",
    fontWeight: "600",
    textAlign: "center",
  },
  amenityTypeText: {
    fontSize: 12,
    color: "#ccc",
    fontStyle: "italic",
    textAlign: "center",
  },
  amenityFilterInfo: {
    fontSize: 13,
    color: "#666",
    fontStyle: "italic",
    marginBottom: 8,
    textAlign: "center",
  },
  navigateButton: {
    backgroundColor: "#007AFF",
    padding: 12,
    borderRadius: 25,
    alignItems: "center",
    marginTop: 10,
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  navigateButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: 16,
  },
  buttonContainer: {
    position: "absolute",
    bottom: 300,
    right: 20,
    alignItems: "center",
    gap: 10,
  },
  resetButton: {
    backgroundColor: "white",
    padding: 10,
    borderRadius: 50,
    elevation: 5,
    alignItems: "center",
    justifyContent: "center",
    width: 50,
    height: 50,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  resetButtonText: {
    fontSize: 20,
  },
  clusterMarker: {
    backgroundColor: "#ADD8E6",
    borderRadius: 50,
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#FFF",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  clusterMarkerLarge: {
    backgroundColor: "#ADD8E6",
    borderRadius: 50,
    width: 60,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#FFF",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  clusterText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFF",
  },
  filterContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-around",
    alignItems: "center",
    padding: 10,
    backgroundColor: "white",
    elevation: 3,
    zIndex: 1000,
  },
  filterMenuContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 250,
    height: "100%",
    backgroundColor: "rgba(255,255,255,0.9)",
    zIndex: 1050,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  filterMenuCloseButton: {
    position: "absolute",
    top: 10,
    right: 10,
    padding: 10,
    backgroundColor: "#fff",
    borderRadius: 20,
    zIndex: 1,
  },
  filterMenuCloseText: {
    fontSize: 24,
    fontWeight: "bold",
  },
  filterMenuTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 10,
  },
  carDistanceInput: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    padding: 10,
    marginBottom: "95%",
  },
  modalContainer: {
    backgroundColor: "white",
    padding: 20,
    marginHorizontal: 20,
    borderRadius: 10,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
    color: "#333",
  },
  input: {
    backgroundColor: "transparent",
    marginBottom: 15,
    color: "black",
  },
  track: {
    height: 5,
    borderRadius: 5,
    backgroundColor: "rgb(227, 225, 254)",
  },
  thumb: {
    height: 20,
    width: 20,
    backgroundColor: "#6200EE",
  },
  dropdown: {
    marginBottom: 15,
    backgroundColor: "white",
    borderRadius: 5,
    padding: 10,
  },
  subtitle: {
    fontSize: 16,
    color: "#444",
    marginBottom: 10,
  },
  chipContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
    marginBottom: 15,
  },
  chip: {
    backgroundColor: "#EEE",
    borderRadius: 20,
    paddingHorizontal: 12,
  },
  chipSelected: {
    backgroundColor: "#6200EE",
    color: "white",
  },
  closeButton: {
    marginTop: 15,
    marginBottom: 10,
    backgroundColor: "#6200EE",
    borderRadius: 10,
  },
  rating: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
    color: "#007AFF",
  },
  reviewsContainer: {
    maxHeight: 200,
    width: "100%",
    marginVertical: 15,
    backgroundColor: "#f8f8f8",
    padding: 15,
    borderRadius: 12,
  },
  reviewItem: {
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
    paddingBottom: 10,
  },
  reviewAuthor: {
    fontWeight: "bold",
    fontSize: 15,
    marginBottom: 4,
    color: "#333",
  },
  reviewText: {
    fontSize: 14,
    color: "#555",
    lineHeight: 20,
  },
  photosContainer: {
    flexDirection: "row",
    marginVertical: 15,
    width: "100%",
  },
  photo: {
    width: 140,
    height: 110,
    borderRadius: 10,
    marginRight: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  expandedPhotoContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.9)",
  },
  expandedPhoto: {
    width: "90%",
    height: "80%",
    resizeMode: "contain",
    borderRadius: 12,
  },
  PlaceModalContainer: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  PlaceModalContent: {
    width: "90%",
    maxWidth: 500,
    padding: 24,
    backgroundColor: "#fff",
    borderRadius: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 8,
  },
  PlaceModalTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 12,
    color: "#333",
  },
  PlaceModalAddress: {
    fontSize: 15,
    color: "#666",
    textAlign: "center",
    marginBottom: 20,
  },
  PlaceModalCloseButton: {
    paddingVertical: 12,
    paddingHorizontal: 32,
    backgroundColor: "#007AFF",
    borderRadius: 25,
    marginTop: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    width: "80%",
    alignItems: "center",
  },
  PlaceModalCloseText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 16,
  },
  searchContainer: {
    width: "94%",
    alignSelf: "center",
    zIndex: 10,
  },
  amenityFilterContainer: {
    width: "100%",
    position: "absolute",
    zIndex: 9,
    paddingTop: 5,
    paddingBottom: 5,
  },
  infoButtonContainer: {
    position: "absolute",
    bottom: 30,
    right: 20,
    alignItems: "center",
  },
  infoButton: {
    backgroundColor: "#007AFF",
    padding: 10,
    borderRadius: 50,
    elevation: 5,
    alignItems: "center",
    justifyContent: "center",
    width: 50,
    height: 50,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  infoButtonText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "white",
  },
});
