export const amenitiesCategories = {
  restaurant: 7315,
  cafe: 9376,
  parking: 7369,
  hospital: 7321,
  hotel: 7314,
};

// Change from array to object with key-value pairs
export const googleTypes: Record<string, string> = {
  restaurant: "restaurant",
  cafe: "cafe",
  parking: "parking",
  hospital: "hospital",
  hotel: "hotel",
  gas_station: "gas_station",
  supermarket: "supermarket",
  shopping_mall: "shopping_mall",
  pharmacy: "pharmacy",
  bank: "bank",
  atm: "atm",
  gym: "gym",
  museum: "museum",
  library: "library",
  movie_theater: "movie_theater",
  post_office: "post_office",
};

// Expanded mapping of amenity types to Google Places API types
// This helps match more accurately when filtering places
export const amenityTypeMapping: Record<string, string[]> = {
  restaurant: [
    "restaurant",
    "meal_delivery",
    "meal_takeaway",
    "food",
    "dining",
    "bistro",
    "eatery",
    "grill",
    "diner",
    "steakhouse",
    "fast_food",
  ],
  cafe: [
    "cafe",
    "bakery",
    "coffee_shop",
    "coffee",
    "tea",
    "dessert",
    "pastry",
    "tea_room",
    "breakfast",
  ],
  hospital: [
    "hospital",
    "health_care",
    "medical_center",
    "doctor",
    "emergency_room",
    "clinic",
    "healthcare",
    "medical",
    "emergency",
    "care_center",
    "urgent_care",
    "medical_facility",
  ],
  hotel: [
    "lodging",
    "hotel",
    "motel",
    "guest_house",
    "inn",
    "resort",
    "hostel",
    "accommodation",
    "bed_and_breakfast",
    "vacation_rental",
  ],
  gas_station: [
    "gas_station",
    "fuel",
    "electric_vehicle_charging_station",
    "petrol_station",
    "service_station",
    "filling_station",
    "gas",
    "charging_station",
    "ev_charging",
  ],
  supermarket: [
    "supermarket",
    "grocery_or_supermarket",
    "convenience_store",
    "food_market",
    "grocer",
    "groceries",
    "grocery_store",
    "market",
    "shop",
    "food_store",
    "food_shop",
    "hypermarket",
  ],
  convenience_store: [
    "convenience_store",
    "grocery_or_supermarket",
    "store",
    "food",
    "general_store",
    "corner_store",
    "mini_market",
    "local_store",
    "quick_shop",
    "bodega",
    "mart",
    "deli",
  ],
  shopping_mall: [
    "shopping_mall",
    "shopping_center",
    "department_store",
    "marketplace",
    "mall",
    "shopping",
    "retail",
    "shopping_complex",
    "shopping_plaza",
    "shopping_arcade",
    "outlet_mall",
    "galleria",
  ],
  pharmacy: [
    "pharmacy",
    "drugstore",
    "health",
    "chemist",
    "apothecary",
    "dispensary",
    "medical_supply",
    "medications",
  ],
  bank: [
    "bank",
    "finance",
    "financial_institution",
    "credit_union",
    "banking",
    "money",
    "financial_services",
  ],
  atm: [
    "atm",
    "finance",
    "money_service",
    "cash_machine",
    "cash_point",
    "cashpoint",
    "cash_dispenser",
    "bancomat",
  ],
  gym: [
    "gym",
    "fitness_center",
    "health_club",
    "sports_center",
    "recreation_center",
    "fitness",
    "workout",
    "exercise",
    "training",
    "athletic_center",
    "spa",
    "wellness_center",
  ],
  bar: [
    "bar",
    "night_club",
    "pub",
    "tavern",
    "lounge",
    "nightlife",
    "cocktail_bar",
    "brewery",
    "club",
    "wine_bar",
  ],
  museum: [
    "museum",
    "art_gallery",
    "tourist_attraction",
    "exhibition",
    "gallery",
    "cultural_center",
    "historic_site",
    "heritage",
    "display",
  ],
  library: [
    "library",
    "book_store",
    "books",
    "bookshop",
    "reading_room",
    "public_library",
    "media_library",
    "information_center",
  ],
  movie_theater: [
    "movie_theater",
    "cinema",
    "theatre",
    "theater",
    "film",
    "multiplex",
    "amc",
    "entertainment_center",
    "screening",
  ],
  post_office: [
    "post_office",
    "courier_service",
    "mail",
    "shipping",
    "postal",
    "postal_service",
    "mail_service",
    "package_service",
  ],
  parking: [
    "parking",
    "parking_lot",
    "parking_space",
    "parking_garage",
    "car_park",
    "parking_structure",
    "paid_parking",
    "garage",
  ],
};
